package com.figaf.integration.tpm.enumtypes;

public enum TpmObjectType {
    CLOUD_COMPANY_PROFILE,
    CLOUD_SUBSIDIARY,
    CLOUD_TRADING_PARTNER,
    CLOUD_COMMUNICATION_PARTNER,
    CLOUD_AGREEMENT_TEMPLATE,
    CLOUD_AGREEMENT,
    CLOUD_MIG,
    CLOUD_B2B_SCENARIO,

    PD_PARTNER
}
